# Generated by Django 6.0.3 on 2026-03-27 11:43

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Author',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
            ],
        ),
        migrations.CreateModel(
            name='Genre',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='Publisher',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
            ],
        ),
        migrations.CreateModel(
            name='Book',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255)),
                ('subtitle', models.CharField(blank=True, max_length=255)),
                ('description', models.TextField(blank=True)),
                ('language', models.CharField(default='ru', max_length=50)),
                ('publication_year', models.PositiveIntegerField(blank=True, null=True)),
                ('isbn', models.CharField(blank=True, db_index=True, max_length=20)),
                ('pages', models.PositiveIntegerField(blank=True, null=True)),
                ('cover_type', models.CharField(blank=True, choices=[('soft', 'Мягкая'), ('hard', 'Твёрдая'), ('integral', 'Интегральная')], max_length=20)),
                ('height_mm', models.PositiveIntegerField(blank=True, null=True)),
                ('width_mm', models.PositiveIntegerField(blank=True, null=True)),
                ('thickness_mm', models.PositiveIntegerField(blank=True, null=True)),
                ('age_rating', models.CharField(blank=True, choices=[('0+', '0+'), ('6+', '6+'), ('12+', '12+'), ('16+', '16+'), ('18+', '18+')], max_length=4)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('authors', models.ManyToManyField(blank=True, related_name='books', to='admin_panel.author')),
                ('genres', models.ManyToManyField(blank=True, related_name='books', to='admin_panel.genre')),
                ('publisher', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='admin_panel.publisher')),
            ],
        ),
    ]
