# Generated by Django 6.0.3 on 2026-03-27 12:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('admin_panel', '0005_book_genre_book_publication_year_book_publisher'),
    ]

    operations = [
        migrations.AddField(
            model_name='book',
            name='cover_type',
            field=models.CharField(choices=[('hard', 'Твердый'), ('soft', 'Мягкий')], default='soft', max_length=10, verbose_name='Тип переплёта'),
        ),
        migrations.AddField(
            model_name='book',
            name='language',
            field=models.CharField(default='', max_length=50, verbose_name='Язык издания'),
        ),
        migrations.AddField(
            model_name='book',
            name='pages',
            field=models.PositiveIntegerField(blank=True, null=True, verbose_name='Количество страниц'),
        ),
        migrations.AlterField(
            model_name='book',
            name='genre',
            field=models.CharField(default='', max_length=100, verbose_name='Жанр'),
        ),
    ]
