# Generated by Django 6.0.3 on 2026-03-27 12:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('admin_panel', '0006_book_cover_type_book_language_book_pages_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='book',
            name='old_price',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True, verbose_name='Старая цена / цена до скидки'),
        ),
        migrations.AddField(
            model_name='book',
            name='stock',
            field=models.PositiveIntegerField(default=0, verbose_name='Остаток на складе'),
        ),
        migrations.AddField(
            model_name='book',
            name='vat_rate',
            field=models.CharField(choices=[('0', 'Без НДС'), ('10', '10%'), ('20', '20%')], default='20', max_length=2, verbose_name='Ставка НДС'),
        ),
        migrations.AlterField(
            model_name='book',
            name='cover_type',
            field=models.CharField(choices=[('hard', 'Твердый'), ('soft', 'Мягкий')], default='hard', max_length=10, verbose_name='Тип переплёта'),
        ),
    ]
