# Generated by Django 6.0.3 on 2026-03-27 12:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('admin_panel', '0007_book_old_price_book_stock_book_vat_rate_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='book',
            name='author_oblozh',
            field=models.CharField(default='', max_length=100, verbose_name='Автор на обложке'),
        ),
        migrations.AddField(
            model_name='book',
            name='height',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=6, null=True, verbose_name='Высота с упаковкой (см)'),
        ),
        migrations.AddField(
            model_name='book',
            name='length',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=6, null=True, verbose_name='Длина с упаковкой (см)'),
        ),
        migrations.AddField(
            model_name='book',
            name='weight',
            field=models.DecimalField(blank=True, decimal_places=3, max_digits=6, null=True, verbose_name='Вес с упаковкой (кг)'),
        ),
        migrations.AddField(
            model_name='book',
            name='width',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=6, null=True, verbose_name='Ширина с упаковкой (см)'),
        ),
        migrations.AlterField(
            model_name='book',
            name='stock',
            field=models.PositiveIntegerField(default=1, verbose_name='Остаток на складе'),
        ),
        migrations.AlterField(
            model_name='book',
            name='vat_rate',
            field=models.CharField(choices=[('0', 'Без НДС'), ('10', '10%'), ('20', '20%')], default='Без НДС', max_length=2, verbose_name='Ставка НДС'),
        ),
    ]
