# Generated by Django 6.0.3 on 2026-03-27 12:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('admin_panel', '0009_bookphoto_book_photos'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='book',
            name='photos',
        ),
        migrations.AddField(
            model_name='book',
            name='images',
            field=models.ImageField(blank=True, null=True, upload_to='book_images/', verbose_name='Фото'),
        ),
        migrations.DeleteModel(
            name='BookPhoto',
        ),
    ]
