# Generated by Django 6.0.3 on 2026-03-27 12:49

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('admin_panel', '0010_remove_book_photos_book_images_delete_bookphoto'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='book',
            name='images',
        ),
        migrations.CreateModel(
            name='BookImage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to='book_images/', verbose_name='Фото')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Дата добавления')),
                ('book', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='book_images', to='admin_panel.book', verbose_name='Книга')),
            ],
            options={
                'verbose_name': 'Фото книги',
                'verbose_name_plural': 'Фотографии книг',
                'ordering': ['created_at'],
            },
        ),
    ]
