# Generated by Django 6.0.3 on 2026-03-27 12:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('admin_panel', '0011_remove_book_images_bookimage'),
    ]

    operations = [
        migrations.AddField(
            model_name='book',
            name='photo',
            field=models.ImageField(blank=True, null=True, upload_to='book_photos/', verbose_name='Фото'),
        ),
        migrations.DeleteModel(
            name='BookImage',
        ),
    ]
