# Generated by Django 6.0.3 on 2026-03-27 12:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('admin_panel', '0012_book_photo_delete_bookimage'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='book',
            name='photo',
        ),
        migrations.AddField(
            model_name='book',
            name='photos',
            field=models.JSONField(blank=True, default=list, verbose_name='Фотографии'),
        ),
    ]
