# Generated by Django 6.0.3 on 2026-03-27 13:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('admin_panel', '0013_remove_book_photo_book_photos'),
    ]

    operations = [
        migrations.AlterField(
            model_name='book',
            name='photos',
            field=models.JSONField(blank=True, default=list, null=True, verbose_name='Фотографии'),
        ),
    ]
