# Generated by Django 6.0.3 on 2026-04-21 12:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('admin_panel', '0016_fix_vat_rate_default'),
    ]

    operations = [
        migrations.AddField(
            model_name='book',
            name='sku',
            field=models.CharField(blank=True, max_length=50, null=True, unique=True, verbose_name='Артикул'),
        ),
    ]
