# Generated by Django 6.0.3 on 2026-04-21 12:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('admin_panel', '0017_book_sku'),
    ]

    operations = [
        migrations.AddField(
            model_name='book',
            name='condition',
            field=models.CharField(blank=True, choices=[('excellent', 'Отличная'), ('good', 'Хорошая')], max_length=20, null=True, verbose_name='Сохранность'),
        ),
    ]
