# Generated by Django 6.0.3 on 2026-04-21 12:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('admin_panel', '0018_book_condition'),
    ]

    operations = [
        migrations.AddField(
            model_name='book',
            name='series',
            field=models.CharField(blank=True, max_length=200, null=True, verbose_name='Серия'),
        ),
    ]
