# Generated by Django 5.2 on 2026-05-16 13:28

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('admin_panel', '0022_alter_book_isbn_max_length'),
    ]

    operations = [
        migrations.CreateModel(
            name='EksmoBook',
            fields=[
            ],
            options={
                'verbose_name': 'Книга (Эксмо)',
                'verbose_name_plural': 'Каталог — Эксмо',
                'proxy': True,
                'indexes': [],
                'constraints': [],
            },
            bases=('admin_panel.book',),
        ),
        migrations.CreateModel(
            name='ManualBook',
            fields=[
            ],
            options={
                'verbose_name': 'Книга (админка)',
                'verbose_name_plural': 'Каталог — админка',
                'proxy': True,
                'indexes': [],
                'constraints': [],
            },
            bases=('admin_panel.book',),
        ),
    ]
