# Generated by Django 5.2 on 2026-05-25 12:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('admin_panel', '0023_sync_model_state'),
    ]

    operations = [
        migrations.CreateModel(
            name='OzonTemplate',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200, verbose_name='Название шаблона')),
                ('file', models.FileField(upload_to='ozon_templates/', verbose_name='Excel файл')),
                ('description', models.TextField(blank=True, verbose_name='Описание')),
                ('is_active', models.BooleanField(default=True, verbose_name='Активный')),
                ('uploaded_at', models.DateTimeField(auto_now_add=True, verbose_name='Дата загрузки')),
            ],
            options={
                'verbose_name': 'Шаблон Ozon',
                'verbose_name_plural': 'Шаблоны Ozon',
                'ordering': ['-uploaded_at'],
            },
        ),
    ]
