# Generated by Django 5.2 on 2026-06-02 11:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('admin_panel', '0025_alter_book_weight'),
    ]

    operations = [
        migrations.AlterField(
            model_name='book',
            name='height',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=6, null=True, verbose_name='Высота с упаковкой (мм)'),
        ),
        migrations.AlterField(
            model_name='book',
            name='length',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=6, null=True, verbose_name='Длина с упаковкой (мм)'),
        ),
        migrations.AlterField(
            model_name='book',
            name='width',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=6, null=True, verbose_name='Ширина с упаковкой (мм)'),
        ),
    ]
