# Generated by Django 5.2 on 2026-06-02 11:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('admin_panel', '0026_update_dimensions_to_mm'),
    ]

    operations = [
        migrations.AlterField(
            model_name='book',
            name='weight',
            field=models.DecimalField(blank=True, decimal_places=4, max_digits=8, null=True, verbose_name='Вес с упаковкой (г)'),
        ),
    ]
