# Generated by Django 5.2 on 2026-06-15 06:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('admin_panel', '0029_alter_eksmobook_options'),
    ]

    operations = [
        migrations.AlterField(
            model_name='book',
            name='genre',
            field=models.CharField(default='', max_length=100, verbose_name='Направление'),
        ),
    ]
