# Generated by Django 5.2 on 2026-06-16 09:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('admin_panel', '0031_book_paper_type'),
    ]

    operations = [
        migrations.AlterField(
            model_name='book',
            name='paper_type',
            field=models.CharField(blank=True, choices=[('offset', 'Офсетная'), ('art', 'Художественная'), ('newsprint', 'Газетная'), ('recycled', 'Макулатурная'), ('kremovaya', 'Кремовая'), ('design', 'Дизайнерская'), ('karton', 'Картон'), ('coated', 'Мелованная')], max_length=20, null=True, verbose_name='Тип бумаги'),
        ),
    ]
