# Generated by Django 5.2 on 2026-06-16 09:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('admin_panel', '0032_alter_book_paper_type'),
    ]

    operations = [
        migrations.AddField(
            model_name='book',
            name='hashtags',
            field=models.CharField(blank=True, max_length=200, null=True, verbose_name='Хештеги'),
        ),
    ]
