# Generated by Django 5.2 on 2026-06-16 10:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('admin_panel', '0033_book_hashtags'),
    ]

    operations = [
        migrations.AddField(
            model_name='book',
            name='Target_audience',
            field=models.CharField(default='', max_length=100, verbose_name='Целевая аудитория'),
        ),
    ]
