# Generated by Django 5.2 on 2026-06-16 10:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('admin_panel', '0034_book_target_audience'),
    ]

    operations = [
        migrations.RenameField(
            model_name='book',
            old_name='Target_audience',
            new_name='target_audience',
        ),
        migrations.AddField(
            model_name='book',
            name='age_restrictions',
            field=models.CharField(default='', max_length=100, verbose_name='Возрастные ограничения'),
        ),
    ]
