# Generated by Django 5.2 on 2026-06-16 11:03

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('admin_panel', '0035_rename_target_audience_book_target_audience_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='book',
            name='age_restrictions',
        ),
    ]
