# Generated by Django 5.2 on 2026-06-16 11:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('admin_panel', '0036_remove_book_age_restrictions'),
    ]

    operations = [
        migrations.AddField(
            model_name='book',
            name='age_restrictions',
            field=models.CharField(default='', max_length=100, verbose_name='Возрастные ограничения'),
        ),
    ]
