# Generated by Django 5.2 on 2026-06-16 17:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('admin_panel', '0038_alter_book_age_restrictions_alter_book_author_oblozh_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='book',
            name='paper_type',
            field=models.CharField(blank=True, choices=[('offset', 'Офсетная'), ('art', 'Художественная'), ('newsprint', 'Газетная'), ('recycled', 'Макулатурная'), ('kremovaya', 'Кремовая'), ('design', 'Дизайнерская'), ('karton', 'Картон'), ('coated', 'Мелованная глянцевая'), ('coatedMat', 'Меловання матовая'), ('kartograf', 'Картографическая'), ('vtorichka', 'Вторичной переработки'), ('vlaga', 'Влагостойкая')], max_length=20, null=True, verbose_name='Тип бумаги'),
        ),
    ]
