# Generated by Django 5.2 on 2026-06-16 18:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('admin_panel', '0040_alter_book_paper_type'),
    ]

    operations = [
        migrations.AlterField(
            model_name='book',
            name='cover_type',
            field=models.CharField(choices=[('hard', 'Твердый переплет'), ('soft', 'Мягкая обложка'), ('softSuper', 'Мягкая обложка, суперобложка'), ('klapan', 'Обложка с клапанами'), ('klapanSuper', 'Обложка с клапанами, суперобложка'), ('poluKozha', 'Полукожаный переплет'), ('hardSuper', 'Твердый переплет, суперобложка'), ('textile', 'Тканевый переплет'), ('textileSuper', 'Тканевый переплет, суперобложка'), ('block', 'Блок для переплета'), ('Bumvinyl', 'Бумвинил'), ('integral', 'Интегральный переплет'), ('integralSuper', 'Интегральный переплет, суперобложка'), ('leather', 'Кожаный переплет'), ('sheet', 'Листовое издание'), ('copper', 'Медный переплет')], default='hard', max_length=20, verbose_name='Тип переплёта'),
        ),
    ]
