# Generated by Django 5.2 on 2026-06-16 18:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('admin_panel', '0041_alter_book_cover_type'),
    ]

    operations = [
        migrations.AlterField(
            model_name='book',
            name='condition',
            field=models.CharField(blank=True, choices=[('excellent', 'Отличная'), ('good', 'Хорошая'), ('veriGood', 'Очень хорошая'), ('satisfactorily', 'Удовлетворительная'), ('bad', 'Плохая')], default='good', max_length=20, verbose_name='Сохранность'),
        ),
        migrations.AlterField(
            model_name='book',
            name='paper_type',
            field=models.CharField(blank=True, choices=[('offset', 'Офсетная'), ('art', 'Художественная'), ('newsprint', 'Газетная'), ('recycled', 'Макулатурная'), ('kremovaya', 'Кремовая'), ('design', 'Дизайнерская'), ('karton', 'Картон'), ('coated', 'Мелованная глянцевая'), ('coatedMat', 'Меловання матовая'), ('kartograf', 'Картографическая'), ('vtorichka', 'Вторичной переработки'), ('vlaga', 'Влагостойкая'), ('puhlaya', 'Пухлая'), ('samokley', 'Самоклеющаяся'), ('tipograf', 'Типографская')], default='offset', max_length=20, verbose_name='Тип бумаги'),
        ),
    ]
