# Generated by Django 5.2 on 2026-06-16 18:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('admin_panel', '0042_alter_book_condition_alter_book_paper_type'),
    ]

    operations = [
        migrations.AlterField(
            model_name='book',
            name='language',
            field=models.CharField(default='russian', max_length=50, verbose_name='Язык издания'),
        ),
    ]
