# Generated by Django 5.2 on 2026-06-16 18:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('admin_panel', '0043_alter_book_language'),
    ]

    operations = [
        migrations.AlterField(
            model_name='book',
            name='language',
            field=models.CharField(choices=[('russian', 'Русский'), ('english', 'Английский'), ('french', 'Французский'), ('german', 'Немецкий')], default='russian', max_length=50, verbose_name='Язык издания'),
        ),
    ]
