# Generated by Django 5.2 on 2026-06-16 19:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('admin_panel', '0044_alter_book_language'),
    ]

    operations = [
        migrations.AlterField(
            model_name='book',
            name='age_restrictions',
            field=models.CharField(blank=True, choices=[('18+', '18+'), ('16+', '16+'), ('14+', '14+'), ('12+', '12+'), ('10+', '10+'), ('9+', '9+')], default='18+', max_length=100, verbose_name='Возрастные ограничения'),
        ),
        migrations.AlterField(
            model_name='book',
            name='target_audience',
            field=models.CharField(blank=True, choices=[('for adults', 'Для взрослых'), ('for children', 'Для детей')], default='for adults', max_length=100, verbose_name='Целевая аудитория'),
        ),
    ]
