# Generated by Django 5.2 on 2026-06-16 19:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('admin_panel', '0045_alter_book_age_restrictions_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='book',
            name='book_type',
            field=models.CharField(blank=True, choices=[('printed book', 'Печатная книга'), ('second', 'Second-hand книга'), ('bookinist', 'Букинистика')], default='printed book', max_length=20, verbose_name='Тип книги'),
        ),
    ]
