# Generated by Django 5.2 on 2026-06-16 19:41

import admin_panel.models
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('admin_panel', '0046_book_book_type'),
    ]

    operations = [
        migrations.AlterField(
            model_name='book',
            name='category',
            field=models.ForeignKey(blank=True, default=admin_panel.models.get_default_category, null=True, on_delete=django.db.models.deletion.SET_NULL, to='admin_panel.category', verbose_name='Категория'),
        ),
    ]
