# Generated by Django 5.2 on 2026-06-16 19:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('admin_panel', '0047_alter_book_category'),
    ]

    operations = [
        migrations.AlterField(
            model_name='book',
            name='length',
            field=models.CharField(blank=True, max_length=6, null=True, verbose_name='Длина с упаковкой (мм)'),
        ),
    ]
