# Generated by Django 5.2 on 2026-06-16 19:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('admin_panel', '0048_alter_book_length'),
    ]

    operations = [
        migrations.AlterField(
            model_name='book',
            name='length',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=6, null=True, verbose_name='Длина с упаковкой (мм)'),
        ),
    ]
