# Generated by Django 5.2 on 2026-06-17 15:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('admin_panel', '0049_alter_book_length'),
    ]

    operations = [
        migrations.AlterField(
            model_name='book',
            name='book_type',
            field=models.CharField(blank=True, choices=[('printed book', 'Печатная книга'), ('second', 'Second-hand книга'), ('bookinist', 'Букинистика'), ('print_on_demand', 'Печать по требованию')], default='printed book', max_length=20, verbose_name='Тип книги'),
        ),
    ]
