# Generated by Django 5.2 on 2026-06-17 20:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('admin_panel', '0051_alter_book_genre'),
    ]

    operations = [
        migrations.AddField(
            model_name='book',
            name='tnved_code',
            field=models.CharField(blank=True, default='4901100000', max_length=10, null=True, verbose_name='ТН ВЭД коды ЕАЭС'),
        ),
    ]
