# Generated by Django 5.2 on 2026-06-18 12:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('admin_panel', '0054_alter_book_tnved_code'),
    ]

    operations = [
        migrations.AlterField(
            model_name='book',
            name='tnved_code',
            field=models.CharField(blank=True, default='4901100000 - Книги, брошюры, листовки и аналогичные печатные издания в виде отдельных листов, сфальцованные или несфальцованные', max_length=200, null=True, verbose_name='ТН ВЭД коды ЕАЭС'),
        ),
    ]
