# Generated by Django 5.2 on 2026-06-18 13:56

from django.db import migrations, models


def fix_empty_ozon_ids(apps, schema_editor):
    Category = apps.get_model('admin_panel', 'Category')
    for cat in Category.objects.filter(ozon_category_id=''):
        cat.ozon_category_id = f'auto_{cat.pk or cat.name[:20]}'
        cat.save(update_fields=['ozon_category_id'])


class Migration(migrations.Migration):

    dependencies = [
        ('admin_panel', '0055_alter_book_tnved_code'),
    ]

    operations = [
        migrations.RunPython(fix_empty_ozon_ids, reverse_code=migrations.RunPython.noop),
        migrations.AlterField(
            model_name='category',
            name='ozon_category_id',
            field=models.CharField(blank=True, max_length=50, unique=True, verbose_name='ID категории Озон'),
        ),
    ]
