# Generated by Django 5.2 on 2026-06-18 18:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('admin_panel', '0056_fix_category_ozon_id_blank'),
    ]

    operations = [
        migrations.AddField(
            model_name='book',
            name='illustrator',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='Иллюстратор'),
        ),
    ]
