# Generated by Django 5.2 on 2026-06-19 06:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('admin_panel', '0058_book_translator'),
    ]

    operations = [
        migrations.AddField(
            model_name='book',
            name='is_adult',
            field=models.BooleanField(default=False, verbose_name='Признак 18+'),
        ),
    ]
