# Generated by Django 5.2 on 2026-06-19 07:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('admin_panel', '0059_book_is_adult'),
    ]

    operations = [
        migrations.AlterField(
            model_name='book',
            name='is_adult',
            field=models.BooleanField(choices=[('yes', 'есть')], default=False, verbose_name='Признак 18+'),
        ),
    ]
