# Generated by Django 5.2 on 2026-06-19 07:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('admin_panel', '0060_book_is_adult2'),
    ]

    operations = [
        migrations.AlterField(
            model_name='book',
            name='is_adult',
            field=models.BooleanField(choices=[('yes', 'Есть'), ('no', 'Нет')], default='no', verbose_name='Признак 18+'),
        ),
    ]
