# Generated by Django 5.2 on 2026-06-19 17:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('admin_panel', '0063_book_is_adult5'),
    ]

    operations = [
        migrations.AlterField(
            model_name='book',
            name='is_adult',
            field=models.CharField(blank=True, choices=[('yes', 'Да'), ('no', 'Нет')], default='no', verbose_name='Признак 18+'),
        ),
    ]
