# Generated by Django 5.2 on 2026-06-20 05:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('admin_panel', '0064_book_is_adult6'),
    ]

    operations = [
        migrations.AlterField(
            model_name='book',
            name='author',
            field=models.CharField(blank=True, default='', max_length=100, verbose_name='Автор'),
        ),
    ]
