# Generated by Django 5.2 on 2026-06-20 06:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('admin_panel', '0065_alter_book_author'),
    ]

    operations = [
        migrations.AlterField(
            model_name='book',
            name='genre',
            field=models.CharField(blank=True, choices=[('antic', 'Античная литература'), ('artbook', 'Артбук'), ('fable', 'Басни'), ('business', 'Бизнес'), ('biography', 'Биография'), ('boevic', 'Боевик'), ('military', 'Военное дело'), ('graphic_novel', 'Графический роман'), ('detective', 'Детектив'), ('home_garden', 'Дом и сад'), ('early_childhood', 'Дошкольное развитие детей'), ('drama', 'Драматургия'), ('information_technology', 'Информационные технологии'), ('art_culture', 'Искусство и культура'), ('history', 'История'), ('comic', 'Комикс'), ('beauty_health', 'Красота и здоровье'), ('cooking', 'Кулинария'), ('romance', 'Любовный роман'), ('manga', 'Манга'), ('manhwa', 'Манхва'), ('manhua', 'Маньхуа'), ('medicine', 'Медицина'), ('memoirs', 'Мемуары'), ('mystery', 'Мистика'), ('young_adult', 'Молодежная и подростковая литература (Young Adult)'), ('scientific', 'Научная и научно-популярная литература'), ('satire', 'Сатира, юмор'), ('sovetsk', 'Советские писатели'), ('pedagogy', 'Педагогика и логопедия'), ('politics', 'Политика и политология'), ('university', 'Пособие для вузов, ссузов, аспирантуры'), ('foreign_language', 'Пособие для изучения иностранных языков'), ('exam_prepEGE', 'Пособие для подготовки к ЕГЭ'), ('exam_prepOGE', 'Пособие для подготовки к ОГЭ'), ('exam_prepVPR', 'Пособие для подготовки к итоговому тестированию и ВПР'), ('school', 'Пособие для школы'), ('poetry', 'Поэзия'), ('law', 'Право и юриспруденция'), ('adventure', 'Приключения'), ('prose', 'Проза'), ('psychology', 'Психология'), ('journalism', 'Публицистика'), ('travel', 'Путешествия и туризм'), ('ranobe', 'Ранобэ'), ('religion', 'Религия'), ('self_development', 'Саморазвитие'), ('dictionary', 'Словарь'), ('sports', 'Спорт'), ('thriller', 'Триллер'), ('horror', 'Ужасы'), ('fantastic', 'Фантастика'), ('fantasy', 'Фэнтези'), ('hobby_creativity', 'Хобби и творчество'), ('esoterica_spirituality', 'Эзотерика и духовные практики'), ('economics_finance', 'Экономика и финансы'), ('encyclopedia_reference', 'Энциклопедия, справочник'), ('epic_folklore', 'Эпос и фольклор')], default='fantastic', max_length=100, verbose_name='Направление'),
        ),
    ]
