# Generated by Django 5.2 on 2026-06-21 17:27

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('admin_panel', '0073_add_genre_modern'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='manualbook',
            options={'permissions': [('add_book_manual', 'Может добавлять книги в Каталог — админка'), ('delete_book_manual', 'Может удалять книги из Каталог — админка'), ('change_book_manual', 'Может редактировать книги в Каталог — админка'), ('view_book_manual', 'Может просматривать книги в Каталог — админка')], 'verbose_name': 'Книга (админка)', 'verbose_name_plural': 'Каталог — админка'},
        ),
    ]
