# Generated by Django 5.2 on 2026-06-24 09:41

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('admin_panel', '0076_alter_book_genre'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddIndex(
            model_name='book',
            index=models.Index(fields=['source', 'created_at'], name='book_source_created_idx'),
        ),
        migrations.AddIndex(
            model_name='book',
            index=models.Index(fields=['source', 'isbn'], name='book_source_isbn_idx'),
        ),
        migrations.AddIndex(
            model_name='book',
            index=models.Index(fields=['created_at'], name='book_created_at_idx'),
        ),
        migrations.AddIndex(
            model_name='book',
            index=models.Index(fields=['isbn'], name='book_isbn_idx'),
        ),
        migrations.AddIndex(
            model_name='book',
            index=models.Index(fields=['genre'], name='book_genre_idx'),
        ),
        migrations.AddIndex(
            model_name='book',
            index=models.Index(fields=['publisher'], name='book_publisher_idx'),
        ),
        migrations.AddIndex(
            model_name='book',
            index=models.Index(fields=['publication_year'], name='book_pub_year_idx'),
        ),
        migrations.AddIndex(
            model_name='book',
            index=models.Index(fields=['category'], name='book_category_idx'),
        ),
        migrations.AddIndex(
            model_name='book',
            index=models.Index(fields=['book_type'], name='book_book_type_idx'),
        ),
        migrations.AddIndex(
            model_name='book',
            index=models.Index(fields=['language'], name='book_language_idx'),
        ),
    ]
