# Generated by Django 5.2 on 2026-06-24 09:49

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('admin_panel', '0077_book_book_source_created_idx_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddIndex(
            model_name='book',
            index=models.Index(fields=['author'], name='book_author_idx'),
        ),
        migrations.AddIndex(
            model_name='book',
            index=models.Index(fields=['series'], name='book_series_idx'),
        ),
        migrations.AddIndex(
            model_name='book',
            index=models.Index(fields=['condition'], name='book_condition_idx'),
        ),
        migrations.AddIndex(
            model_name='book',
            index=models.Index(fields=['cover_type'], name='book_cover_type_idx'),
        ),
    ]
