# Generated by Django 5.2 on 2026-06-24 11:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('admin_panel', '0078_book_book_author_idx_book_book_series_idx_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='book',
            name='isbn_digits',
            field=models.CharField(blank=True, db_index=True, max_length=13, verbose_name='ISBN только цифры'),
        ),
    ]
