# Generated by Django 5.2 on 2026-06-24 11:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('admin_panel', '0079_book_isbn_digits'),
    ]

    operations = [
        migrations.AlterField(
            model_name='book',
            name='isbn_digits',
            field=models.CharField(blank=True, db_index=True, max_length=20, verbose_name='ISBN только цифры'),
        ),
    ]
