# Generated by Django 5.2 on 2026-06-24 11:38

from django.db import migrations
def normalize_isbn(value):
    return ''.join(c for c in (value or '') if c.isdigit())
def backfill_isbn_digits(apps, schema_editor):
    Book = apps.get_model('admin_panel', 'Book')
    batch_size = 1000
    queryset = Book.objects.filter(isbn_digits='').exclude(isbn__isnull=True).exclude(isbn='')
    total = queryset.count()
    updated = 0
    for book in queryset.iterator(chunk_size=batch_size):
        book.isbn_digits = normalize_isbn(book.isbn)
        book.save(update_fields=['isbn_digits'])
        updated += 1
        if updated % batch_size == 0:
            print(f'  Обновлено {updated} из {total}')
    print(f'✅ Итого обновлено: {updated}')
class Migration(migrations.Migration):
    atomic = False
    dependencies = [
        ('admin_panel', '0080_alter_book_isbn_digits'),
    ]
    operations = [
        migrations.RunPython(backfill_isbn_digits, reverse_code=migrations.RunPython.noop),
    ]
