# Generated by Django 5.2 on 2026-06-25 09:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('admin_panel', '0081_backfill_isbn_digits'),
    ]

    operations = [
        migrations.AlterField(
            model_name='book',
            name='source',
            field=models.CharField(choices=[('manual', 'Админка'), ('eksmo', 'Импорт Эксмо'), ('ast', 'Импорт АСТ')], db_index=True, default='manual', max_length=10, verbose_name='Источник'),
        ),
    ]
