# Generated by Django 5.2 on 2026-06-25 09:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('admin_panel', '0082_alter_book_source'),
    ]

    operations = [
        migrations.AlterField(
            model_name='category',
            name='ozon_category_id',
            field=models.CharField(blank=True, max_length=50, null=True, unique=True, verbose_name='ID категории Озон'),
        ),
    ]
