# Generated by Django 5.2 on 2026-06-25 09:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('admin_panel', '0084_alter_book_age_restrictions'),
    ]

    operations = [
        migrations.AlterField(
            model_name='book',
            name='is_adult',
            field=models.CharField(blank=True, choices=[('yes', 'Да'), ('no', 'Нет')], default='yes', verbose_name='Признак 18+'),
        ),
    ]
