# Generated by Django 5.2 on 2026-06-25 09:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('admin_panel', '0085_alter_book_is_adult'),
    ]

    operations = [
        migrations.AlterField(
            model_name='book',
            name='target_audience',
            field=models.CharField(blank=True, choices=[('for adults', 'Для взрослых'), ('for children', 'Для детей')], default='or children', max_length=100, verbose_name='Целевая аудитория'),
        ),
    ]
