# Generated by Django 5.2 on 2026-06-28 12:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('admin_panel', '0086_alter_book_target_audience'),
    ]

    operations = [
        migrations.AddField(
            model_name='ozontemplate',
            name='year_from',
            field=models.PositiveIntegerField(blank=True, help_text='Книги с publication_year >= этого значения попадут в данный шаблон. Если оставить пустым, шаблон считается дефолтным.', null=True, verbose_name='Год от (включительно)'),
        ),
    ]
