# Generated by Django 5.2 on 2026-06-28 13:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('admin_panel', '0087_ozontemplate_year_from'),
    ]

    operations = [
        migrations.AddField(
            model_name='ozontemplate',
            name='year_to',
            field=models.PositiveIntegerField(blank=True, help_text='Если указано — книги с publication_year <= этого значения могут попасть сюда.', null=True, verbose_name='Год до (включительно)'),
        ),
        migrations.AlterField(
            model_name='ozontemplate',
            name='year_from',
            field=models.PositiveIntegerField(blank=True, help_text='Если указано — книги с publication_year >= этого значения могут попасть сюда.', null=True, verbose_name='Год от (включительно)'),
        ),
    ]
