# Generated by Django 5.2 on 2026-07-30 11:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('admin_panel', '0088_ozontemplate_year_to_alter_ozontemplate_year_from'),
    ]

    operations = [
        migrations.AlterField(
            model_name='book',
            name='paper_type',
            field=models.CharField(blank=True, choices=[('offset', 'Офсетная'), ('art', 'Художественная'), ('newsprint', 'Газетная'), ('recycled', 'Макулатурная'), ('kremovaya', 'Кремовая'), ('design', 'Дизайнерская'), ('karton', 'Картон'), ('coated', 'Мелованная глянцевая'), ('coatedMat', 'Мелованная матовая'), ('kartograf', 'Картографическая'), ('vtorichka', 'Вторичной переработки'), ('vlaga', 'Влагостойкая'), ('puhlaya', 'Пухлая'), ('samokley', 'Самоклеющаяся'), ('tipograf', 'Типографская')], default='offset', max_length=20, verbose_name='Тип бумаги'),
        ),
    ]
