# Generated by Django 5.2 on 2026-07-31 12:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('admin_panel', '0091_alter_book_genre'),
    ]

    operations = [
        migrations.AlterField(
            model_name='book',
            name='language',
            field=models.CharField(choices=[('russian', 'Русский'), ('english', 'Английский'), ('french', 'Французский'), ('german', 'Немецкий'), ('italian', 'Итальянский'), ('spanish', 'Испанский'), ('turkish', 'Турецкий'), ('chinese', 'Китайский'), ('korean', 'Корейский'), ('greek', 'Греческий'), ('portuguese', 'Португальский'), ('arabic', 'Арабский'), ('japanese', 'Японский'), ('vietnamese', 'Вьетнамский'), ('thai', 'Тайский')], default='russian', max_length=50, verbose_name='Язык издания'),
        ),
    ]
