# Generated by Django 5.2 on 2026-08-04 09:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('admin_panel', '0092_alter_book_language'),
    ]

    operations = [
        migrations.AlterField(
            model_name='book',
            name='age_restrictions',
            field=models.CharField(blank=True, choices=[('18+', '18+'), ('16+', '16+'), ('12+', '12+'), ('10+', '10+'), ('9+', '9+'), ('8+', '8+'), ('7+', '7+'), ('6+', '6+'), ('5+', '5+'), ('4+', '4+'), ('3+', '3+'), ('2+', '2+'), ('1+', '1+'), ('0+', '0+')], default='18+', max_length=100, verbose_name='Возрастные ограничения'),
        ),
    ]
