# Generated by Django 5.2 on 2026-08-25 12:01

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('admin_panel', '0090_alter_book_language'),
        ('admin_panel', '0093_alter_book_age_restrictions'),
    ]

    operations = [
    ]
