# Generated by Django 5.2 on 2026-08-25 12:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('admin_panel', '0094_merge_20260825_1501'),
    ]

    operations = [
        migrations.AlterField(
            model_name='book',
            name='language',
            field=models.CharField(choices=[('russian', 'Русский'), ('english', 'Английский'), ('french', 'Французский'), ('german', 'Немецкий'), ('italian', 'Итальянский'), ('spanish', 'Испанский'), ('turkish', 'Турецкий'), ('chinese', 'Китайский'), ('korean', 'Корейский'), ('greek', 'Греческий'), ('portuguese', 'Португальский'), ('arabic', 'Арабский'), ('japanese', 'Японский'), ('vietnamese', 'Вьетнамский'), ('thai', 'Тайский'), ('ukrainian', 'Украинский'), ('polish', 'Польский'), ('latin', 'Латинский'), ('other', 'Другой')], default='russian', max_length=50, verbose_name='Язык издания'),
        ),
        migrations.AlterField(
            model_name='book',
            name='target_audience',
            field=models.CharField(blank=True, choices=[('for adults', 'Для взрослых'), ('for children', 'Для детей')], default='for children', max_length=100, verbose_name='Целевая аудитория'),
        ),
    ]
